#!/bin/bash

#LOGS all logged in Users & Uptime at invocation
# Crites to user_log.log in current directory

#Variables
LOG_FILE_NAME="user_log.log"
LOG_DIR=$PWD
LOG_FILE="$LOG_DIR/$LOG_FILE_NAME"
divider=======================

#Error Code/Values
E_GENERIC="ERROR: Something is wrong here!!"

test -e "$LOG_FILE" || { touch $LOG_FILE || echo "Error: Cannot create log file" ; exit 1; }
test -w "$LOG_FILE" || { echo "Error: Permission Denied on $LOG_FILE " ; exit 1; } 

DATE=`date +%Y-%m-%d:%H:%M:%S` || { echo $E_GENERIC && exit 1; }
UPTIME=`uptime` || {  echo $E_GENERIC && exit 1; }
USERS=`users` || { echo $E_GENERIC && exit 1; }

printf '%s\n%s\n%s\n%s\n%s\n' "$divider$divider$divider" "Date= $DATE" "Users = $USERS" "Uptime = $UPTIME" >> $LOG_FILE

exit 0;

